---
title: "4. Epoching"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{4. Epoching}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor: visual
editor_options:
  chunk_output_type: inline
---

> 🎯 **GOALS**
>
> -   *Learn how to load EEG data into R*
> -   *Visually inspect the raw EEG signal*
> -   *Understand the basics of frequency-domain filtering*

## 4.1 Epoching

-   

```{r, eval=FALSE}
n170_events <- c(1:80)
epo <- epoch_data(eeg_downs, n170_events, time_lim = c(-0.2, 0.8))
```

```{r, eval=FALSE}
epo$epochs
```

```{r, eval=FALSE}
epo$epochs$condition <- ifelse(epo$epochs$event_type <= 40, "face", "car")
epo$epochs$condition <- factor(epo$epochs$condition, levels = c("face", "car"))
epo$epochs
```

## 3.6 Correcting eye artifacts

```{r, eval=FALSE}
ica <- run_ICA(epo, method = "fastica")
```

```{r, eval=FALSE}
browse_data(ica)
```

```{r, eval=FALSE}
filt <- eeg_filter(eeg, 1, 10)
epo <- epoch_data(filt, n170_events, time_lim = c(-0.2, 0.8))
epo <- select_elecs(epo, c("HEOG_left", "HEOG_right", "VEOG_lower"), keep = FALSE)
epo <- rm_baseline(epo, time_lim = c(-0.2, 0.0))
library(ggplot2)
plot_butterfly(epo, time_lim = c(0.0, 0.6)) +
  theme_void() +
  scale_color_viridis_d(option = "mako") +
  theme(
    aspect.ratio = 0.5,
    panel.background = element_rect(fill = NA, color = NA),
    legend.position = "none"
  ) -> p
p$layers[2:3] <- NULL
p$layers[[1]]$aes_params$size <- 4.0
p$layers[[1]]$aes_params$alpha <- 1.0
p

ggsave("butterfly.png")
```
